name: Merge

on:
  issue_comment:
    types: [created, edited]
  check_run:
    types: [completed]
  status:

jobs:
  merge:
    runs-on: ubuntu-20.04
    steps:
      - name: Determine ref for comment
        if: ${{ github.event.issue.pull_request.url }}
        run: echo '::set-env ref=$(curl -s "${{ github.event.issue.pull_request.url }}" | jq -r .head.sha)'

      - uses: actions/checkout@v2
        with:
          ref: ${{ ref }}
      - uses: ./
