name: Merge

on:
  issue_comment:
    types: [created, edited]
  check_run:
    types: [completed]
  status:

jobs:
  merge:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./
